### ISSUE TITLE
ERROR in ./node_modules/sprestlib/dist/sprestlib.js

### ISSUE THREAD

**Issue by azmatzuberi** [gitbrent/SpRestLib#23]
Hi,

I'm using Angular 4 and I'm trying to use: var sprLib = require("sprestlib"); 

I keep getting this error:
ERROR in ./node_modules/sprestlib/dist/sprestlib.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\USER\Documents\spapp\sp-app\node_modules\sprestlib\dist'

regards

**Comment by gitbrent** [comment]
Hi @azmatzuberi,

Thank you for letting me know about this!

I was testing for the `https` module by using require(), which was a bad idea... :-)

Please try the newest code and let me know is the issue is resolved.

**Comment by azmatzuberi** [comment]
Hi gitbrent,

Thanks for updating the code. I'm still experiencing the same issue:
ERROR in ./node_modules/sprestlib/dist/sprestlib.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\user\Documents\spapp\sp-app\node_modules\sprestlib\dist'

**Comment by gitbrent** [comment]
Hi @azmatzuberi,

I've pushed a new version to NPM (1.7.0), so once you've updated, the issue should be resolved.

**Comment by Wireliner** [comment]
Hi @gitbrent ,

I finally managed to make it work. 

So, the following import syntax causes "can't resolve https" error. 

What I did is added "declare var sprLib: any;" in "typings.d.ts", then added "scripts": ["./node_modules/sprestlib/dist/sprestlib.min.js"] in "angular.json" file. 

Regards, 
Zhandos

**Comment by gitbrent** [comment]
Hi @Wireliner ,

Thank you very much for posting the solution.

I'm going to re-open this issue so I can create a demo with Angular to see what can be done with SpRestLib to integrate more seamlessly.

**Comment by gitbrent** [comment]
Updated docs:

### [Library Integration](https://gitbrent.github.io/SpRestLib/docs/feat-integration.html)
